### PR TITLE
setup: created students table

### PR DESCRIPTION
**Pull request by smellslikekeenspirit**
Configured a postgres database locally and created the table in it through Pool

### CODE REVIEW

**Review by MatthewGalan — APPROVED** [review]
Instead of storing the major and college with each student, what if we had a separate table of all the majors (with their corresponding colleges & a major ID), and then just stored the major ID for each student?

I know very little about database management, though, so I'm not married to the idea.

It's looking great, though. Thanks for getting a head start on this!

**Comment by smellslikekeenspirit** [comment]
@MatthewGalan I like the idea about a table of majors and corresponding colleges. Major IDs might hurt readability for the admin and they would have to keep referring to the other table right? Unless we are creating a view for the admin that includes filtering functionality, where they can perform the analytics they wanted to. We can use the 4-letter codes RIT uses for majors though if we are to implement the major ID idea.

**Comment by MatthewGalan** [comment]
> Major IDs might hurt readability for the admin and they would have to keep referring to the other table right?

Admins won't be looking directly at the backend, though, right? We would return the actual major name for the frontend.

> We can use the 4-letter codes RIT uses for majors though if we are to implement the major ID idea.
Good idea!

**Comment by smellslikekeenspirit** [comment]
Yeah, as long as we are creating a view for the admin sounds aok

**Pull request merged**
